name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}  
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install PNPM
        run: npm i pnpm -g

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm-lock.yaml')) }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm i

      - name: Build
        run: yarn build
        env:
          NITRO_PRESET: firebase

      - name: Publish to Cloudflare
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOINUNIFORM }}'
          channelId: live
          projectId: joinuniform
